ARDUINO_DIR = /usr/share/arduino
TARGET = controller
ARDUINO_LIBS = Wire Wire/utility
MCU = atmega328p
F_CPU = 16000000
ARDUINO_PORT = /dev/ttyUSB0
AVRDUDE_ARD_PROGRAMMER = arduino
AVRDUDE_ARD_BAUDRATE = 57600


include /usr/share/arduino/Arduino.mk
